---

- hosts: ngcsdevices
  collections:
    - opengear_om
  connection: httpapi
  gather_facts: no
  tasks:
    - name: Add static routes
      opengear.om.om_static_routes:
        config:
        - destination_address: 192.168.10.14
        state:
          deleted
