---

- hosts: ngcsdevices
  collections:
    - opengear_om
  gather_facts: false
  connection: httpapi
  tasks:
    - name: Add groups
      opengear.om.om_groups:
        config:
        - groupname: test7
          description: This group was added.
          enabled: yes
          mode: scoped
          role: ConsoleUser
          ports:
          - serial/by-opengear-id/port01
          - serial/by-opengear-id/port05
          - serial/by-opengear-id/port16
          - serial/by-opengear-id/port22
        state:
          merged
