---

- hosts: ngcsdevices
  collections:
    - opengear_om
  connection: httpapi
  tasks:
    - name: Delete physif
      opengear.om.om_physifs:
        config:
        - name: init_bnd0
        state:
          deleted
    - name: Add physif
      opengear.om.om_physifs:
        config:
        - enabled: true
          mtu: 1500
          description: A new physif.
          media: bond
          slaves:
          - net1
        state:
          replaced
