---

- hosts: ngcsdevices
  collections:
    - opengear_om
  connection: httpapi
  gather_facts: yes
  tasks:
    - name: Get port info
      opengear.om.om_facts:
        gather_subset: min
        gather_network_resources: ports
        
    - name: Modify ports
      opengear.om.om_ports:
        config:
          ports:
          - id: "{{ item.id }}"
            mode: consoleServer
        state:
          merged
      loop: "{{ ansible_facts['network_resources']['ports']['ports'] }}"
