---

- hosts: ngcsdevices
  collections:
    - opengear_om
  connection: httpapi
  tasks:
    - name: Change Hostname, timezone and time
      opengear.om.om_system:
        config:  
          hostname: OM2100
          timezone: Australia/Sydney
          time: 20:18 Sep 14 2020
