---

- hosts: ngcsdevices
  collections:
    - opengear_om
  connection: httpapi
  tasks:
    - name: Change Auth
      opengear.om.om_auth:
        config:
          mode: local
        state:
          merged
